### ISSUE TITLE
Mecha has failed to launch the hooked client.

### ISSUE THREAD

**Issue by Bruno9931** [x00bence/Mecha#1]
I tried pretty much everything and i'm unable to make it run :(
Any ideas on what im doing wrong?

**Comment by x00bence** [comment]
Hey!

All good, I'm just gonna need some more information. This can happen due to many reasons.

First and foremost, are you trying to run the `mecha_injector.exe` file directly by any chance? This usually triggers that error.
If that's the case, you have to use the `Mecha GUI.exe` file to properly hook your client.

If that's not the case, you're going to have to verify a few things. Please navigate to your League of Legends installation folder ("C:\Riot Games\League of Legends", or something like that), and make sure `mecha_injector.exe` and `mecha_payload.dll` are in the folder. 

Did you compile Mecha yourself or are you using an externally compiled version?

Which antivirus are you using (if any), and have you tried disabling it? Sometimes it mistakenly flags Mecha and/or prevents its method of injection into the client.

Which operating system are you using?

Cannot reproduce on my own machine without more information.

**Comment by Bruno9931** [comment]
Hey, thank you so much for the quick reply.
I'm trying to run the Mecha Gui.exe but i did not know that i had to put mecha_injector.exe and mecha_payload.dll on the league folder. Also the order of things i have to do is sort of confusing (on my part)

After putting both the injector and the .dll on league's folder im able to run the Mecha Gui.exe but im not sure how to proceed from there. Do i run the client & hook? Do i hook before i run the client?
I tried both ways but whenever i press Hook it gives me an error "You are missing needed files for hooking. Please download a fresh version of Mecha or recompile your project".
I did try to recompile as well and it gives me the first error i had.

**Comment by Bruno9931** [comment]
It looks like everything was fine. For some strange reason i had to restart my PC due to windows update. I did not touch a single thing, ran Mecha GUI and everything simply worked..

Thanks for the quick reply and help! Any chance you have discord or any sort of communication? Id like to ask you a few questions regarding the client.

Thanks again!

**Comment by x00bence** [comment]
Glad to hear that!

Yes, I am aware that it might be confusing for people. I am currently in the process of writing better, more fleshed out documentation to make it easier for people to understand Mecha. All in due time. 

The steps are always as follows: 

1. Launch your client 
2. Launch Mecha GUI 
3. Press "Hook"  (Note: Only once is enough. You don't need to hook on every startup.)
4. Everything else will be taken care of, you may relaunch your client as normal

Yes, I do have Discord: `Bence#9206` - Feel free to add me!
